version: '3.9'
services:
  web:
    build: .
    ports:
      - '3010:3000'
    volumes:
      - '.:/usr/src/web'
    links:
      - 'mongodb'
    depends_on:
      - 'mongodb'

  mongodb:
    image: 'mongo:4'
